// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_protocol.proto

package com.dtc.framework.distributed.rpc.proto;

public final class RpcProtocolOuterClass {
  private RpcProtocolOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_AttachmentsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_AttachmentsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dtc_framework_distributed_rpc_proto_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022rpc_protocol.proto\022\'com.dtc.framework." +
      "distributed.rpc.proto\"\223\002\n\nRpcRequest\022\021\n\t" +
      "requestId\030\001 \001(\t\022\023\n\013serviceName\030\002 \001(\t\022\022\n\n" +
      "methodName\030\003 \001(\t\022\026\n\016parameterTypes\030\004 \001(\t" +
      "\022\021\n\targuments\030\005 \001(\014\022\017\n\007timeout\030\006 \001(\003\022Y\n\013" +
      "attachments\030\007 \003(\0132D.com.dtc.framework.di" +
      "stributed.rpc.proto.RpcRequest.Attachmen" +
      "tsEntry\0322\n\020AttachmentsEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\"V\n\013RpcResponse\022\021\n\tre" +
      "questId\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022\024\n\014errorMe" +
      "ssage\030\003 \001(\t\022\016\n\006result\030\004 \001(\0142\200\001\n\013RpcProto" +
      "col\022q\n\004Call\0223.com.dtc.framework.distribu" +
      "ted.rpc.proto.RpcRequest\0324.com.dtc.frame" +
      "work.distributed.rpc.proto.RpcResponseB+" +
      "\n\'com.dtc.framework.distributed.rpc.prot" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_descriptor,
        new java.lang.String[] { "RequestId", "ServiceName", "MethodName", "ParameterTypes", "Arguments", "Timeout", "Attachments", });
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_AttachmentsEntry_descriptor =
      internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_AttachmentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dtc_framework_distributed_rpc_proto_RpcRequest_AttachmentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dtc_framework_distributed_rpc_proto_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dtc_framework_distributed_rpc_proto_RpcResponse_descriptor,
        new java.lang.String[] { "RequestId", "Status", "ErrorMessage", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
