// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_protocol.proto

package com.dtc.framework.distributed.rpc.proto;

public interface RpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dtc.framework.distributed.rpc.proto.RpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <pre>
   * 0: OK, 1: Error
   * </pre>
   *
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string errorMessage = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   * Serialized result
   * </pre>
   *
   * <code>bytes result = 4;</code>
   * @return The result.
   */
  com.google.protobuf.ByteString getResult();
}
