// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_protocol.proto

package com.dtc.framework.distributed.rpc.proto;

public interface RpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dtc.framework.distributed.rpc.proto.RpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string serviceName = 2;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 2;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>string methodName = 3;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>string methodName = 3;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <pre>
   * JSON array of class names
   * </pre>
   *
   * <code>string parameterTypes = 4;</code>
   * @return The parameterTypes.
   */
  java.lang.String getParameterTypes();
  /**
   * <pre>
   * JSON array of class names
   * </pre>
   *
   * <code>string parameterTypes = 4;</code>
   * @return The bytes for parameterTypes.
   */
  com.google.protobuf.ByteString
      getParameterTypesBytes();

  /**
   * <pre>
   * Serialized arguments
   * </pre>
   *
   * <code>bytes arguments = 5;</code>
   * @return The arguments.
   */
  com.google.protobuf.ByteString getArguments();

  /**
   * <code>int64 timeout = 6;</code>
   * @return The timeout.
   */
  long getTimeout();

  /**
   * <code>map&lt;string, string&gt; attachments = 7;</code>
   */
  int getAttachmentsCount();
  /**
   * <code>map&lt;string, string&gt; attachments = 7;</code>
   */
  boolean containsAttachments(
      java.lang.String key);
  /**
   * Use {@link #getAttachmentsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttachments();
  /**
   * <code>map&lt;string, string&gt; attachments = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttachmentsMap();
  /**
   * <code>map&lt;string, string&gt; attachments = 7;</code>
   */
  /* nullable */
java.lang.String getAttachmentsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attachments = 7;</code>
   */
  java.lang.String getAttachmentsOrThrow(
      java.lang.String key);
}
